export const overlayDocument = `<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<style>
*{box-sizing:border-box}html,body{width:100%;height:100%;margin:0;overflow:hidden;background:transparent;font-family:Inter,"Segoe UI",Arial,sans-serif;color:white}.layer{position:absolute;transition:opacity .25s ease,transform .32s cubic-bezier(.2,.8,.2,1);opacity:0;pointer-events:none}.layer.visible{opacity:1;transform:translate(0,0)}#lower{left:6%;bottom:10%;display:flex;align-items:stretch;transform:translateY(36px)}#lower .accent{width:10px;border-radius:8px 0 0 8px;background:#38bdf8}#lower .body{min-width:560px;padding:24px 34px 22px;border:1px solid rgba(255,255,255,.16);border-left:0;border-radius:0 14px 14px 0;background:linear-gradient(120deg,rgba(10,15,24,.96),rgba(20,28,40,.93));box-shadow:0 28px 80px rgba(0,0,0,.45);backdrop-filter:blur(18px)}#lower .name{font-size:35px;font-weight:700;letter-spacing:-.02em}#lower .meta{margin-top:8px;font-size:20px;color:#a7b0c0}#ticker{inset:auto 0 0 0;height:72px;transform:translateY(72px);overflow:hidden;border-top:1px solid rgba(255,255,255,.14);background:rgba(8,12,18,.94)}#ticker .track{display:inline-flex;align-items:center;min-width:100%;height:100%;padding-left:100%;white-space:nowrap;font-size:25px;animation:scroll 22s linear infinite}#ticker[dir=rtl] .track{padding-left:0;padding-right:100%;animation-name:scrollRtl}@keyframes scroll{to{transform:translateX(-100%)}}@keyframes scrollRtl{to{transform:translateX(100%)}}#clock{right:4%;top:5%;transform:translateY(-20px);border:1px solid rgba(255,255,255,.14);border-radius:12px;background:rgba(8,12,18,.86);padding:14px 20px;font:600 26px ui-monospace,monospace;box-shadow:0 16px 50px rgba(0,0,0,.35)}#logo{right:4%;bottom:8%;transform:scale(.85);font-size:25px;font-weight:800;letter-spacing:.16em;text-shadow:0 4px 18px #000}#sponsor{inset:50% auto auto 50%;transform:translate(-50%,-45%) scale(.94);border:1px solid rgba(255,255,255,.16);border-radius:18px;background:rgba(8,12,18,.94);padding:42px 70px;text-align:center;box-shadow:0 30px 100px rgba(0,0,0,.55)}#sponsor.visible{transform:translate(-50%,-50%) scale(1)}#sponsor small{display:block;margin-bottom:12px;font-size:16px;letter-spacing:.18em;text-transform:uppercase;color:#9ca3af}#sponsor strong{font-size:38px}
</style></head><body>
<section id="lower" class="layer"><div class="accent"></div><div class="body"><div class="name"></div><div class="meta"></div></div></section>
<section id="ticker" class="layer"><div class="track"></div></section><section id="clock" class="layer"></section><section id="logo" class="layer">NAS</section><section id="sponsor" class="layer"><small>Presented by</small><strong>Event Sponsor</strong></section>
<script>
const lower=document.querySelector('#lower'),nameEl=lower.querySelector('.name'),metaEl=lower.querySelector('.meta'),accent=lower.querySelector('.accent'),ticker=document.querySelector('#ticker'),track=ticker.querySelector('.track'),clock=document.querySelector('#clock'),logo=document.querySelector('#logo'),sponsor=document.querySelector('#sponsor');let current=null;
function visible(el,on){el.classList.toggle('visible',Boolean(on))}function render(s){current=s;nameEl.textContent=s.lowerThird.name;metaEl.textContent=[s.lowerThird.title,s.lowerThird.organization].filter(Boolean).join(' · ');accent.style.background=s.lowerThird.accentColor;lower.dir=s.lowerThird.direction;visible(lower,s.lowerThird.visible);track.textContent=s.ticker.text;ticker.dir=s.ticker.direction;track.style.animationDuration=Math.max(8,35-s.ticker.speed)+'s';visible(ticker,s.ticker.visible);visible(clock,s.clock.visible);visible(logo,s.logoVisible);visible(sponsor,s.sponsorVisible)}
async function init(){render(await fetch('/state').then(r=>r.json()));const events=new EventSource('/events');events.onmessage=e=>render(JSON.parse(e.data))}setInterval(()=>{if(!current)return;if(current.clock.mode==='clock'){clock.textContent=new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}else if(current.clock.targetTime){const remaining=Math.max(0,new Date(current.clock.targetTime).getTime()-Date.now());clock.textContent=new Date(remaining).toISOString().slice(11,19)}},250);init();
</script></body></html>`

