import { Copy, Download, Radio, Upload } from 'lucide-react'
import type { ProjectDocument } from '../../../../shared/project'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Panel, PanelHeader } from '@/components/ui/panel'
import { useRemoteController } from '@/hooks/use-remote-controller'
import { useProject } from '@/state/project-context'

export function SettingsPage({ project, updateProject }: { project: ProjectDocument; updateProject: (updater: (project: ProjectDocument) => ProjectDocument) => void }): React.JSX.Element {
  const { importProject, exportProject } = useProject()
  const remote = useRemoteController()

  return (
    <div className="page-shell">
      <div className="page-heading"><div><span className="eyebrow">Project configuration</span><h2>Settings</h2><p>Cross-platform project, remote control, and operator preferences.</p></div><Badge tone="ready">Auto saved</Badge></div>
      <div className="grid grid-cols-2 gap-4">
        <Panel><PanelHeader><h3 className="panel-title">Project</h3></PanelHeader><div className="space-y-4 p-4"><label className="settings-field"><span>Project name</span><input value={project.name} onChange={(event) => updateProject((current) => ({ ...current, name: event.target.value }))} /></label><label className="settings-field"><span>Event name</span><input value={project.eventName} onChange={(event) => updateProject((current) => ({ ...current, eventName: event.target.value }))} /></label><div className="grid grid-cols-3 gap-2"><div className="readout"><span>Width</span><strong>{project.canvas.width}</strong></div><div className="readout"><span>Height</span><strong>{project.canvas.height}</strong></div><div className="readout"><span>FPS</span><strong>{project.canvas.fps}</strong></div></div><div className="grid grid-cols-2 gap-2"><Button variant="ghost" onClick={() => void importProject()}><Upload className="size-4" />Import</Button><Button variant="ghost" onClick={() => void exportProject()}><Download className="size-4" />Export</Button></div></div></Panel>
        <Panel><PanelHeader><h3 className="panel-title">Operator</h3></PanelHeader><div className="space-y-3 p-4"><label className="toggle-row"><span><strong>Confirm Program changes</strong><small>Prevent accidental on-air actions.</small></span><input type="checkbox" checked={project.operator.confirmProgramChanges} onChange={(event) => updateProject((current) => ({ ...current, operator: { ...current.operator, confirmProgramChanges: event.target.checked } }))} /></label><label className="toggle-row"><span><strong>Automatic saving</strong><small>Persist project changes after 600 ms.</small></span><input type="checkbox" checked={project.operator.autoSave} onChange={(event) => updateProject((current) => ({ ...current, operator: { ...current.operator, autoSave: event.target.checked } }))} /></label><div className="readout mt-4"><span>Platform</span><strong>{window.nasBroadcast.platform === 'darwin' ? 'macOS' : 'Windows'}</strong></div><div className="readout"><span>Hotkeys</span><strong>{window.nasBroadcast.platform === 'darwin' ? '⌘ 1–6 · ⌘ S' : 'Ctrl 1–6 · Ctrl S'}</strong></div></div></Panel>
        <Panel className="col-span-2"><PanelHeader><div className="flex items-center gap-2"><Radio className="size-4 text-violet-300" /><h3 className="panel-title">Remote Tablet & Roles</h3></div><Badge tone={remote.state.enabled ? 'ready' : 'neutral'}>{remote.state.enabled ? 'LAN active' : 'Disabled'}</Badge></PanelHeader><div className="grid grid-cols-[220px_1fr] gap-4 p-4"><div><p className="text-xs leading-5 text-zinc-500">Starts a local-network control surface with separate Director, Operator, and read-only Viewer access. Tokens stay in memory and rotate after restart.</p><Button className="mt-4 w-full" variant={remote.state.enabled ? 'danger' : 'default'} onClick={() => void (remote.state.enabled ? remote.disable() : remote.enable())}>{remote.state.enabled ? 'Disable remote control' : 'Enable remote control'}</Button></div><div className="space-y-2">{(['directorUrl', 'operatorUrl', 'viewerUrl'] as const).map((key) => { const url = remote.state[key]; return <div key={key} className="flex items-center gap-2 rounded-lg border border-white/[0.06] bg-black/20 p-2.5"><div className="min-w-0 flex-1"><span className="block text-[9px] font-semibold uppercase tracking-[.13em] text-zinc-600">{key.replace('Url', '')}</span><code className="mt-1 block truncate text-[10px] text-zinc-400">{url ?? 'Available after enabling LAN remote'}</code></div><Button aria-label={`Copy ${key}`} size="icon" variant="ghost" disabled={!url} onClick={() => { if (url) window.nasBroadcast.system.copyText(url) }}><Copy className="size-3.5" /></Button></div>})}</div></div></Panel>
      </div>
    </div>
  )
}
